// ----------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a compiler emitter: FACTS.Framework.Analysis.Generators.OperationMethod.ControllerEmitter
//
// Changes to this file may cause incorrect behavior and will be lost when the code is regenerated.
// </auto-generated>
// ----------------------------------------------------------------------------------------------------

using System;
using Microsoft.AspNetCore.Mvc;
using FACTS.Framework.Service;

namespace PFML.Service.Controllers.Sample.ExampleScreen
{

    public class ExampleScreenController : Controller
    {

        ///<summary>Composite object for passing in multiple values to Search method</summary>
        public class SearchRequest
        {
            public string SourceType;
            public string SourceName;
            public string TargetType;
            public string TargetName;
            public string AccessType;
        }

        ///<param name="request">Composite request object for passing in multiple values</param>
        [HttpPost]
        [Route("Sample/ExampleScreen/Search")]
        [OperationMethodFilter]
        public System.Collections.Generic.List<PFML.Shared.Model.DbDtos.SecurityPermissionDto> Search([FromBody]SearchRequest request)
        {
            return PFML.BusinessLogic.Sample.ExampleScreen.ExampleScreenLogic.Search(request.SourceType, request.SourceName, request.TargetType, request.TargetName, request.AccessType);
        }

        [HttpPost]
        [Route("Sample/ExampleScreen/Save")]
        [OperationMethodFilter]
        public void Save([FromBody]PFML.Shared.Model.DbDtos.SecurityPermissionDto securityPermissionDto)
        {
            PFML.BusinessLogic.Sample.ExampleScreen.ExampleScreenLogic.Save(securityPermissionDto);
        }

    }

}
