// ----------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a compiler emitter: FACTS.Framework.Analysis.Generators.OperationMethod.ProxyEmitter
//
// Changes to this file may cause incorrect behavior and will be lost when the code is regenerated.
// </auto-generated>
// ----------------------------------------------------------------------------------------------------

using System;
using System.Threading.Tasks;
using FACTS.Framework.Web;

namespace PFML.Web.ServiceProxies.Sample.Revenue.Search
{

    public static class EmployerSearchProxy
    {

        ///<summary>URL base path location for web service</summary>
        private const string servicePath = "Sample/Revenue/Search/EmployerSearch";

        ///<summary>ASYNC Web Service call: unknown</summary>
        ///<returns>ASYNC task: unknown</returns>
        public static async Task<PFML.Shared.ViewModels.Core.Headers.Agency.SearchCriteria> BlankSearchCriteriaAsync()
        {
            using (OperationClient client = new OperationClient(servicePath, "BlankSearchCriteria"))
            {
                return await client.ReadAsync<PFML.Shared.ViewModels.Core.Headers.Agency.SearchCriteria>();
            }
        }

        ///<summary>Web Service call: unknown</summary>
        public static PFML.Shared.ViewModels.Core.Headers.Agency.SearchCriteria BlankSearchCriteria()
        {
            return BlankSearchCriteriaAsync().Result;
        }

        ///<summary>ASYNC Web Service call: unknown</summary>
        ///<returns>ASYNC task: unknown</returns>
        public static async Task<System.Collections.Generic.List<PFML.Shared.ViewModels.Revenue.Employer>> SearchAsync(string name)
        {
            using (OperationClient client = new OperationClient(servicePath, "Search"))
            {
                client.Value = name;
                return await client.ReadAsync<System.Collections.Generic.List<PFML.Shared.ViewModels.Revenue.Employer>>();
            }
        }

        ///<summary>Web Service call: unknown</summary>
        public static System.Collections.Generic.List<PFML.Shared.ViewModels.Revenue.Employer> Search(string name)
        {
            return SearchAsync(name).Result;
        }

        ///<summary>ASYNC Web Service call: unknown</summary>
        ///<returns>ASYNC task: unknown</returns>
        public static async Task<PFML.Shared.ViewModels.Revenue.Employer> GetEmployerAsync(int ID)
        {
            using (OperationClient client = new OperationClient(servicePath, "GetEmployer"))
            {
                client.Value = ID;
                return await client.ReadAsync<PFML.Shared.ViewModels.Revenue.Employer>();
            }
        }

        ///<summary>Web Service call: unknown</summary>
        public static PFML.Shared.ViewModels.Revenue.Employer GetEmployer(int ID)
        {
            return GetEmployerAsync(ID).Result;
        }

    }

}
