// ----------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a compiler emitter: FACTS.Framework.Analysis.Generators.OperationMethod.ControllerEmitter
//
// Changes to this file may cause incorrect behavior and will be lost when the code is regenerated.
// </auto-generated>
// ----------------------------------------------------------------------------------------------------

using System;
using Microsoft.AspNetCore.Mvc;
using FACTS.Framework.Service;

namespace PFML.Service.Controllers.Sample.Revenue.Search
{

    public class EmployerSearchController : Controller
    {

        [HttpPost]
        [Route("Sample/Revenue/Search/EmployerSearch/BlankSearchCriteria")]
        [OperationMethodFilter]
        public PFML.Shared.ViewModels.Core.Headers.Agency.SearchCriteria BlankSearchCriteria()
        {
            return PFML.BusinessLogic.Sample.Revenue.Search.EmployerSearchLogic.BlankSearchCriteria();
        }

        [HttpPost]
        [Route("Sample/Revenue/Search/EmployerSearch/Search")]
        [OperationMethodFilter]
        public System.Collections.Generic.List<PFML.Shared.ViewModels.Revenue.Employer> Search([FromBody]string name)
        {
            return PFML.BusinessLogic.Sample.Revenue.Search.EmployerSearchLogic.Search(name);
        }

        [HttpPost]
        [Route("Sample/Revenue/Search/EmployerSearch/GetEmployer")]
        [OperationMethodFilter]
        public PFML.Shared.ViewModels.Revenue.Employer GetEmployer([FromBody]int ID)
        {
            return PFML.BusinessLogic.Sample.Revenue.Search.EmployerSearchLogic.GetEmployer(ID);
        }

    }

}
